version: '3'
services:

  db:
    image: mysql
    container_name: db
    restart : unless-stopped
    environment:
      MYSQL_DATABASE: db_${{appName}}
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
      MYSQL_ROOT_PASSWORD: yourrootpassword
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - "8080:80"


  # backend:
  #   image: pitgrouped/${{appName}}-backend
  #   container_name: ${{appName}}-backend
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     - spring.datasource.url=jdbc:mysql://db:3306/db_${{appName}}?useUnicode=true&serverTimezone=Europe/Paris
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:9000"
  #   expose:
  #     - 8080


volumes:
  dbdata:
  